name: Trivy CVE Dependency Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  trivy-scan:
    uses: carvel-dev/release-scripts/.github/workflows/trivy-scan.yml@main
    with:
      repo: carvel-dev/imgpkg
      tool: imgpkg
      goVersion: '1.22'
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      slackWebhookURL: ${{ secrets.SLACK_WEBHOOK_URL }}
